/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/study`; params?: Router.UnknownInputParams; } | { pathname: `/../assets/data/seedData`; params?: Router.UnknownInputParams; } | { pathname: `/../services/DatabaseService`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/SRSLogic`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/CategoryMapper`; params?: Router.UnknownInputParams; } | { pathname: `/setup`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/study`; params?: Router.UnknownOutputParams; } | { pathname: `/../assets/data/seedData`; params?: Router.UnknownOutputParams; } | { pathname: `/../services/DatabaseService`; params?: Router.UnknownOutputParams; } | { pathname: `/../utils/SRSLogic`; params?: Router.UnknownOutputParams; } | { pathname: `/../utils/CategoryMapper`; params?: Router.UnknownOutputParams; } | { pathname: `/setup`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/study${`?${string}` | `#${string}` | ''}` | `/../assets/data/seedData${`?${string}` | `#${string}` | ''}` | `/../services/DatabaseService${`?${string}` | `#${string}` | ''}` | `/../utils/SRSLogic${`?${string}` | `#${string}` | ''}` | `/../utils/CategoryMapper${`?${string}` | `#${string}` | ''}` | `/setup${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/study`; params?: Router.UnknownInputParams; } | { pathname: `/../assets/data/seedData`; params?: Router.UnknownInputParams; } | { pathname: `/../services/DatabaseService`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/SRSLogic`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/CategoryMapper`; params?: Router.UnknownInputParams; } | { pathname: `/setup`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
